const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2016 - 2020",
    title: "SRM Institute Of Science And Technology",
    desc: "Bachelors In Technology (Computer Science And Engineering)- SRM Institute Of Science And Technology",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2013 - 2015",
    title: "High School",
    desc: "High School- Birla School Pilani",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2009 - 2012",
    title: "High School",
    desc: "High School- Birla School Pilani",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "February 2025 - Present",
    title: "Software Engineer 2",
    desc: "Software Engineer 2 at ZEPTO",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "March 2023 - January 2025",
    title: "Software Engineer 1 (Mobile Apps)",
    desc: "Software Engineer 1 (Mobile Apps) at Kotak811 (Kotak Mahindra Bank)",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "September 2020 - March 2023",
    title: "Associate Software Engineer (DWS- Inteliserve)",
    desc: "Associate Software Engineer (DWS- Inteliserve) - Unisys",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "February 2020 - July 2020",
    title: "Android Development Intern",
    desc: "Android Development Intern - SenSen Networks",
  },
];
export default Data;
